### ISSUE TITLE
NTSC filter is there a corresponding glsl shader?

### ISSUE THREAD

**Issue by mantou132** [lukexor/tetanes#144]
Recently I implemented filter with webgl in my project.

tetanes NTSC filter effect, it gives a little chromatic aberration around the edges of the image, which in turn makes the image less harsh:

![Screenshot 2023-04-01 21_52_42](https://user-images.githubusercontent.com/3841872/229293230-025f4cd3-0b3e-4ae8-8b1b-53dd3a5e5821.png)

use [`image-rendering: auto;`](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering):

![Screenshot 2023-04-01 21_54_20](https://user-images.githubusercontent.com/3841872/229293291-4b548d61-0294-405e-bb5f-f9f354c7bd97.png)

I tried to rewrite the ntsc filter of tetanes into a shader, but couldn't

I tried several shaders from shadertoy, but I still like the ntsc fiter from tetanes:

https://www.shadertoy.com/view/ldXGRf this shader makes the fps of the emulator only 10, and only 30 in [high-performance mode](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#parameters:~:text=GPU%20is%20available.-,powerPreference,-A%20hint%20to)

https://www.shadertoy.com/view/XtlSD7 this shader works very well, but it is very different from the ntsc filter of tetanes

![Screenshot 2023-04-01 21_49_12](https://user-images.githubusercontent.com/3841872/229293007-a7883605-7be3-4c9e-83f5-8649986cb4d5.png)

This is just a problem I encountered, not a bug or feature request of tetanes

thanks tetanes.

**Comment by lukexor** [comment]
That's cool! Yeah I can't take credit for the filter, but it was really hard to adapt from C++ to Rust and also convert to a lookup table to keep it performant because it tanked the FPS originally. I don't use shaders (yet) in Tetanes but I'm sure it could be converted to one.

I'm currently working on another project for a Vulkan game engine. I don't have as much time to develop as I used to now with a 14 month old son, but eventually I'm going to rewrite pix-engine (which is what Tetanes uses to render) to Vulkan with shaders which I'll bring over to Tetanes so eventually there will be a shader done and some big boosts to performance as I'll be adding SIMD operations.

Here are the original sources from Bisqwit:

https://youtu.be/X9q5E-LCvTg
https://bisqwit.iki.fi/jutut/kuvat/programming_examples/nesemu1/

**Comment by mantou132** [comment]
Because I have too little understanding of NES and NTSC, I do not understand its NTSC video output, and the code of Bisqwit is even more incomprehensible.

However, I found a [shader](https://www.shadertoy.com/view/lsfGD2) on shadertoy through "Glitch Art" as a keyword. I tried to streamline it. The effect is very similar to the NTSC Filter of tetness:

![Screenshot 2023-04-02 15_08_57](https://user-images.githubusercontent.com/3841872/229338047-ff1c4cef-b252-497b-80cf-861edc107ee0.png)

I wrote a Rust game some time ago(I am a rust novice) and compiled it into WASM and run on the Web. The pixel rendering was written by myself, so I also want to use SIMD. It seems that Rust programming WASM will automatically optimize to SIMD, but I'm not sure how he did. SIMD can only do some simple operations, I don't know how to apply it to my project. So I look forward to how you use SIMD to optimize performance. 

I wish you a happy life

**Comment by lukexor** [comment]
If you're still interested in converting this to a shader, it shouldn't be too hard. I've attached a NTSC palette lookup table that you could plug into any fragment shader as a plain array and then you just need to have the fragment shader do the following computations per pixel. So for example, if you passed a `vec2` of UV data into your shader representing x/y positions of the NES screen starting from the top-left.

```
#version 450

layout (location = 0) in vec4 in_color;             // NES RGB palette color for this pixel
layout (location = 1) in vec2 uv;                       // X/Y coordinate for this pixel
layout (location = 2) in vec4 prev_color;        // Previous RGB palette color for this pixel, which may require an extra framebuffer for the previous frame
layout (location = 3) in int frame_number;     // The frame number

layout (location = 0) out vec4 out_color;

uniform int NTSC_PALETTE[98304] = [
    # NTSC Palette lookup values...
];

void main() {
    int x = uv.x;
    int y = uv.y;
    int ntsc_color = 0;
    if (x != 0) {
        int even_phase = (frame_number & 1) == 1;
        int phase = (2 + y * 341 + x + even_phase) % 3;
        int color_index  = phase + (prev_color & 0x3F) * 3 + in_color * 3 * 64;
        ntsc_color = NTSC_PALLETE[color_index];
    }

    out_color = vec4(
        ((ntsc_color >> 16) & 0xFF) / 256,
        ((ntsc_color >> 8) & 0xFF / 256,
        (ntsc_color & 0xFF) / 256,
        1.0
    );
}
```

Note, this is just an example. I haven't tested this since I don't have an emulator that uses GLSL shaders. This formula was originally written for 0-255 values, but shaders typically deal with 0.0 - 1.0, so it may be more performant to pre-divide all of the NTSC_PALETTE entries by 256 to bring them in range.

The basic idea with this algorithm is to pre-compute every NTSC palette signal combination, roughly based on this article: https://www.nesdev.org/wiki/NTSC_video#Emulating_in_C++_code

**Comment by metallic77** [comment]
Lukexor, in_color and prev_color are vec4 how are they going to work in an int? How would we change it to work globally and not only on NES?

**Comment by lukexor** [comment]
I forgot to think through this fully. Internally, the colors in the framebuffer in TetaNES are u16 values for each pixel which are not in RGB format. They are actually indexes into the NES color palette. See https://www.nesdev.org/wiki/PPU_palettes

So for example, `in_color` here and `prev_color` are actually palette indexes where a value of $06 is a red color.

What the NTSC filter is doing is mapping a palette index into an approximated NTSC signal value with a certain luma and chroma where the signal oscillates on per frame.

I'd have to completely re-design the NTSC filter to take in RGB for it to work as a generic NTSC filter for something other than the NES.
