### ISSUE TITLE
Saving state corrupts the ROM

### ISSUE THREAD

**Issue by alexmozaidze** [lukexor/tetanes#51]
Saving and loading the state themselves seem to work as intended, but when I try to open the same ROM again after state-save it just doesn't launch. Here's what `RUST_BACKTRACE=1` said:
```
 INFO  tetanes::cartridge > Loaded `Downloads/Ninja Gaiden (USA).nes` - Mapper: 1 - Sxrom/MMC1, PRG ROM: 8, CHR ROM: 16, Mirroring: Horizontal, Battery: false
thread 'main' panicked at 'Invalid opcode $02 XXX #IMP encountered!', /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tetanes-0.7.0/src/cpu/instr.rs:1088:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/core/src/panicking.rs:107:14
   2: tetanes::cpu::instr::<impl tetanes::cpu::Cpu>::xxx
   3: <tetanes::cpu::Cpu as tetanes::common::Clocked>::clock
   4: tetanes::nes::Nes::run
   5: tetanes::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I'm certain it doesn't happen to all ROMs, attempting to run another ROM where I didn't save-state works just fine.

**Comment by lukexor** [comment]
Thanks for reporting - Yeah it definitely seems specific to certain ROMS. I've tried some other Sxrom/MMC1 games and don't have the same issue.

Typically when it panics with an invalid opcode it's because the CPU is trying to read and parse instructions from the wrong area in the ROM. I suspect some variable isn't being saved or loaded correctly in one of the many structs which results in the mapper trying to read memory from the incorrect place. I'll have do do a full audit of all the serialization code to figure it out.

I do have an upcoming huge version release in the `next` branch that is likely to include an entirely new form of data serialization which is less error-prone.

**Comment by lukexor** [comment]
Found the source of the issue! Ninja Gaiden does bank swapping of memory regions. The loading state wasn't correctly setting the correct memory banks after the bank registers were loaded from the file. Nice catch!
